version: '3.0'
services:
  reverse: 
    image: nginx:1.23.3-alpine 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
      - ./js:/etc/nginx/js
    ports:
      - 8085:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
